### PR TITLE
Manifest access cleanup

### PR DESCRIPTION
**Pull request by rgoldberg**
Please see commits for changes.

I cleaned up 4 files.

I performed only one type of cleanup per commit to make it easy to see each step of the cleanup.

The earlier commits are very simple cleanups, like adding @Override, or organizing imports, etc.

The later commits are more useful, reusing code instead of using copied code in multiple places, fixing up some minor bugs & minor performance inefficiencies along the way, and enabling a few optional configs (that have the same default behavior as current AP if the config option isn't specified).

### CODE REVIEW

**Comment by davydotcom** [comment]
cannot use bootstrap changes those should always be hardcoded to true for extraction of assets. These settings are NOT to be used with grails anyway.

**Comment by davydotcom** [comment]
isEnableDigets and isSkipNonDifests were specifically removed form grails. Grails ALWAYS compiles digested versions only as its servlet is smart enough to still serve non digested versions

**Comment by rgoldberg** [comment]
- Without this change, the plugin will generate URLs (both in GSPs and when rewriting URLs in HTML & CSS files) that include the digest even if the assets are served by some other server or CDN via the grails.assets.url setting.  This other server or CDN might not be able to serve assets under both the digested and undigested URLs.  So having these options is really useful, the code works, if you don't explicitly change the settings it behaves exactly as if the settings don't even exist, and most people won't use either setting, but for the people who need them, you can leave them in as undocumented or experimental.
- If you still won't allow the use of these 2 settings, will you accept a PR with all the commits except the last one, which is the only one that enables the 2 settings?  This will:
 - clean up the code
 - have more code reuse
 - fix some existing bugs
 - enable me to easily maintain a fork that allows the 2 settings that I need

**Comment by davydotcom** [comment]
I don't see how a cdn would not be able to serve both sets of files that is why we have the storagePath setting I always sends out both sets of files so that a cdn is able to always serve both digested or non

**Comment by rgoldberg** [comment]
The main issue is getting all the other commits into AP, not the last one, since I can easily maintain a fork of you accept the other commits.

About the the CDN not serving both sets of files: sorry, I should have left that out (I've been working for a long time straight and wasn't thinking 100% clearly).  The issue is the rewriting of URLs in HTML & CSS files.  We also use JS files, and the links there aren't rewritten, and can't all be rewritten since some are obtained via xhr calls, or concatenated by JS, etc.  Also, links can be generated by JS in HTML files, too.  So, we must have our files available without digests.  If we have to have them without digests, what's the point of also serving them under the digested URL?  All that does is require clients to download & cache 2 copies of the same file that can also somehow get out of sync on our CDN.  Since we change the base URL of our CDN on every release, assets under non-digested URLs will still always point to the same version, and can still be cached forever, since any change to an asset will only be released with a new version, which would have a new CDN base URL.  So there's no point in having digests at all for us.  And all they do is decrease performance, and make code harder to debug, etc.

**Pull request closed without merging**
