### PR TITLE
Revert trimLeadingSlash changes

### PR DESCRIPTION
**Pull request by AlexKovynev**
Fix for call with null param and perhaps fix https://github.com/bertramdev/grails-asset-pipeline/issues/337

### CODE REVIEW

**Comment by davydotcom** [comment]
this makes no sense as to why you would want to mod trimLeadingSlash to convert a null string to a blank string

**Comment by AlexKovynev** [comment]
I am not an author of plugins at this time, but look at this

https://github.com/stefanogualdi/grails-ckeditor/blob/master/grails-app/controllers/grails/plugins/ckeditor/OpenFileManagerConnectorController.groovy

"${resource(dir: 'js/ofm')}",
"${resource(dir: 'js/ofm/images/fileicons')}",

With null string all fine,with 3.0.15 it works

**Comment by AlexKovynev** [comment]
It's look like "resource()" does not found asset and continue to search in static path. But this is not happen when all crushed with exception.

**Comment by davydotcom** [comment]
not the issue, closing

**Pull request closed without merging**
