### PR TITLE
Fixed repeated context path issue

### PR DESCRIPTION
**Pull request by rgoldberg**
Fixed issue #312

### CODE REVIEW

**Comment by davydotcom** [comment]
an enum seems a tad overkill here

**Comment by rgoldberg** [comment]
It works.  It doesn't degrade performance.  It's a few lines.  What other option is there?

**Comment by rgoldberg** [comment]
@davydotcom: Any way to merge this, since it fixes a known production bug?

**Comment by davydotcom** [comment]
ill merge and clean up. dont use `\` newline fills.

**Pull request merged**
