### PR TITLE
BuildConfig.groovy cleanup

### PR DESCRIPTION
**Pull request by rgoldberg**
`BuildConfig.groovy` cleanup.  This PR is branched from the branch for PR #309, so if you want to accept both, you can either merge #309 first, then this, or you could just close #309 and only accept this, since this includes the #309 changes.

The branch of #304 is now branched from this branch.  It looks like you won't accept #304, but, if you do, the same situation applies there, too.

### CODE REVIEW

**Comment by rgoldberg** [comment]
Rebased on current AP

**Comment by davydotcom** [comment]
removes a fix for grails 2.4.2

**Comment by rgoldberg** [comment]
In commit dc36eebe820b6862775fa899b160e13700a1e587, you upgraded `app.grails.version=2.4.2`, and added:

    // Temporary inclusion due to bug in 2.4.2
    compile("cglib:cglib-nodep:2.2.2") {
        export = false
    }

Now, `app.grails.version=2.5.1`.

Was the bug not fixed since 2.4.2?

Or, instead of it being needed to support `app.grails.version=2.4.2`, it's actually necessary to support any Grails 2.4.2 app running AP at all, then why did you add the comment about it being temporary?

In the latter case, wouldn't the fix have to be permanent to support Grails 2.4.2 apps anytime in the future?

Or, were you just planning on someday no longer supporting 2.4.2 apps?

Given that there probably won't be many more Grails 2.x releases, why would you drop support for 2.4.2 apps sometime in the future?

**Comment by davydotcom** [comment]
I will probably transition to only supporting Grails 2.5.x later in 2016 due to groovy version

**Pull request closed without merging**
